[build]
  command = "npm install --prefix backend"

[functions]
  directory = "backend/functions"
  included_files = ["backend/functions/**/*.html"]

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200